#!/usr/bin/env node

/**
 * 🚀 Sekolahku Backend Setup Wizard
 * Interactive setup script untuk konfigurasi backend pertama kali
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt) {
  return new Promise(resolve => {
    rl.question(prompt, resolve);
  });
}

function log(message, type = 'info') {
  const icons = {
    info: '📝',
    success: '✅',
    warning: '⚠️ ',
    error: '❌',
    question: '❓',
  };
  console.log(`\n${icons[type]} ${message}`);
}

function generateRandomSecret(length = 32) {
  const crypto = require('crypto');
  return crypto.randomBytes(length).toString('hex');
}

async function main() {
  console.log('\n╔═══════════════════════════════════════════════════╗');
  console.log('║    🎓 Sekolahku Backend Setup Wizard             ║');
  console.log('╚═══════════════════════════════════════════════════╝\n');

  // Check if .env already exists
  const envPath = path.join(__dirname, '.env');
  if (fs.existsSync(envPath)) {
    const existing = await question('✅ .env file already exists. Overwrite? (y/n): ');
    if (existing.toLowerCase() !== 'y') {
      log('Setup cancelled', 'info');
      process.exit(0);
    }
  }

  log('Let\'s configure your environment...', 'question');

  // Environment
  console.log('\n📌 Environment');
  const env = await question('  Node environment (development/staging/production) [development]: ') || 'development';

  // Database
  console.log('\n📌 Database Configuration');
  const dbHost = await question('  Database host [localhost]: ') || 'localhost';
  const dbPort = await question('  Database port [3306]: ') || '3306';
  const dbUser = await question('  Database user [db_sekolah]: ') || 'db_sekolah';
  const dbPassword = await question('  Database password [123]: ') || '123';
  const dbName = await question('  Database name [db_sekolah]: ') || 'db_sekolah';

  // Server
  console.log('\n📌 Server Configuration');
  const port = await question('  Server port [3000]: ') || '3000';

  // JWT Secrets
  console.log('\n📌 JWT Secrets');
  let accessSecret, refreshSecret;
  
  if (env === 'production') {
    log('⚠️  Production mode detected. Generating strong secrets...', 'warning');
    accessSecret = generateRandomSecret(32);
    refreshSecret = generateRandomSecret(32);
    log(`Generated JWT_ACCESS_SECRET: ${accessSecret.substring(0, 16)}...`, 'success');
    log(`Generated JWT_REFRESH_SECRET: ${refreshSecret.substring(0, 16)}...`, 'success');
  } else {
    const useGenerated = await question('  Generate random secrets? (y/n) [y]: ');
    if (useGenerated.toLowerCase() !== 'n') {
      accessSecret = generateRandomSecret(32);
      refreshSecret = generateRandomSecret(32);
      log('Secrets generated', 'success');
    } else {
      accessSecret = await question('  JWT Access Secret: ');
      refreshSecret = await question('  JWT Refresh Secret: ');
    }
  }

  // CORS
  console.log('\n📌 CORS Configuration');
  let corsOrigin = 'http://localhost:5173';
  if (env === 'production') {
    corsOrigin = await question('  Allowed frontend URL: ');
  } else {
    corsOrigin = await question('  Allowed frontend URL [http://localhost:5173]: ') || corsOrigin;
  }

  // Gemini API (optional)
  console.log('\n📌 AI Services (Optional)');
  const geminiKey = await question('  Gemini API key (leave empty to skip): ');

  // Generate .env content
  const envContent = `# Generated by setup wizard at ${new Date().toISOString()}
# See SETUP.md for detailed documentation

PORT=${port}
NODE_ENV=${env}

DB_HOST=${dbHost}
DB_PORT=${dbPort}
DB_USER=${dbUser}
DB_PASSWORD=${dbPassword}
DB_NAME=${dbName}
DB_CONNECTION_LIMIT=10

JWT_ACCESS_SECRET=${accessSecret}
JWT_REFRESH_SECRET=${refreshSecret}
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

CORS_ORIGIN=${corsOrigin}

${geminiKey ? `GEMINI_API_KEY=${geminiKey}` : '# GEMINI_API_KEY=your-api-key'}
`;

  // Write .env
  try {
    fs.writeFileSync(envPath, envContent);
    log('.env file created successfully', 'success');
  } catch (error) {
    log(`Failed to write .env: ${error.message}`, 'error');
    process.exit(1);
  }

  // Summary
  console.log('\n╔═══════════════════════════════════════════════════╗');
  console.log('║           ✅ Setup Complete!                     ║');
  console.log('╚═══════════════════════════════════════════════════╝\n');

  console.log('📋 Summary:');
  console.log(`   Environment: ${env}`);
  console.log(`   Database: ${dbUser}@${dbHost}:${dbPort}/${dbName}`);
  console.log(`   Server Port: ${port}`);
  console.log(`   Frontend URL: ${corsOrigin}`);

  console.log('\n📚 Next steps:\n');
  console.log('   1️⃣  Create database (if not exists):');
  console.log(`       mysql -u root -p`);
  console.log(`       CREATE DATABASE ${dbName};`);
  console.log(`       CREATE USER '${dbUser}'@'localhost' IDENTIFIED BY '${dbPassword}';`);
  console.log(`       GRANT ALL PRIVILEGES ON ${dbName}.* TO '${dbUser}'@'localhost';`);
  console.log(`       FLUSH PRIVILEGES;`);
  
  console.log('\n   2️⃣  Run database migrations:');
  console.log('       npm run migrate');
  
  console.log('\n   3️⃣  Start development server:');
  console.log('       npm run dev');

  console.log('\n   4️⃣  Test API:');
  console.log(`       curl http://localhost:${port}/api/v1/health`);

  console.log('\n💡 For more information, see SETUP.md\n');

  rl.close();
}

main().catch(error => {
  log(`Setup failed: ${error.message}`, 'error');
  process.exit(1);
});
